package usecase

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/masterfabric-go/masterfabric/internal/application/generation/dto"
	docModel "github.com/masterfabric-go/masterfabric/internal/domain/document/model"
	"github.com/masterfabric-go/masterfabric/internal/domain/llm"
	profileModel "github.com/masterfabric-go/masterfabric/internal/domain/projectprofile/model"
	qmodel "github.com/masterfabric-go/masterfabric/internal/domain/questionnaire/model"
	tenantModel "github.com/masterfabric-go/masterfabric/internal/domain/tenant/model"
	domainErr "github.com/masterfabric-go/masterfabric/internal/shared/errors"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

type mockDocumentRepo struct{ mock.Mock }

func (m *mockDocumentRepo) Create(ctx context.Context, doc *docModel.GeneratedDocument) error {
	return m.Called(ctx, doc).Error(0)
}
func (m *mockDocumentRepo) GetByID(ctx context.Context, id uuid.UUID) (*docModel.GeneratedDocument, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*docModel.GeneratedDocument), args.Error(1)
}
func (m *mockDocumentRepo) ListByWorkspace(ctx context.Context, workspaceID uuid.UUID, limit int) ([]*docModel.GeneratedDocument, error) {
	args := m.Called(ctx, workspaceID, limit)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*docModel.GeneratedDocument), args.Error(1)
}

type stubLLMProvider struct {
	name string
	resp llm.GenerateResponse
	err  error
}

func (s *stubLLMProvider) Name() string { return s.name }
func (s *stubLLMProvider) Generate(ctx context.Context, req llm.GenerateRequest) (llm.GenerateResponse, error) {
	if s.err != nil {
		return llm.GenerateResponse{}, s.err
	}
	return s.resp, nil
}
func (s *stubLLMProvider) Health(ctx context.Context) (llm.ProviderHealth, error) {
	return llm.ProviderHealth{Provider: s.name, Healthy: true}, nil
}

func setupGenerateFixture(t *testing.T) (
	orgID, wsID uuid.UUID,
	wsRepo *mockWorkspaceRepo,
	profileRepo *mockProfileRepo,
	setRepo *mockSetRepo,
	questionRepo *mockQuestionRepo,
	answerRepo *mockAnswerRepo,
	docRepo *mockDocumentRepo,
) {
	t.Helper()
	orgID = uuid.New()
	wsID = uuid.New()
	setID := uuid.New()

	wsRepo = new(mockWorkspaceRepo)
	profileRepo = new(mockProfileRepo)
	setRepo = new(mockSetRepo)
	questionRepo = new(mockQuestionRepo)
	answerRepo = new(mockAnswerRepo)
	docRepo = new(mockDocumentRepo)

	wsRepo.On("GetByID", orgContext(orgID), wsID).Return(&tenantModel.Workspace{
		ID:                        wsID,
		OrganizationID:            orgID,
		Name:                      "Studio WS",
		Slug:                      "studio-ws",
		PreferredDocumentLanguage: "tr",
		Status:                    tenantModel.WorkspaceStatusActive,
	}, nil)

	profileRepo.On("GetByWorkspaceID", orgContext(orgID), wsID).Return(&profileModel.Profile{
		OrganizationID:            orgID,
		WorkspaceID:               wsID,
		ProjectName:               "Reporter",
		PreferredDocumentLanguage: "tr",
		Frontend:                  profileModel.EmptyJSONObject,
		Backend:                   profileModel.EmptyJSONObject,
		Data:                      profileModel.EmptyJSONObject,
		Infrastructure:            profileModel.EmptyJSONObject,
		AI:                        profileModel.EmptyJSONObject,
		DevelopmentStandards:      profileModel.EmptyJSONObject,
	}, nil)

	setRepo.On("GetDefault", orgContext(orgID), orgID).Return(&qmodel.QuestionnaireSet{
		ID:  setID,
		Key: "studio-default",
	}, nil)
	questionRepo.On("ListBySetID", orgContext(orgID), setID).Return([]*qmodel.Question{}, nil)
	answerRepo.On("ListByWorkspace", orgContext(orgID), wsID).Return([]*qmodel.Answer{}, nil)

	return orgID, wsID, wsRepo, profileRepo, setRepo, questionRepo, answerRepo, docRepo
}

func TestGenerateDocument_SucceedsWithMockProvider(t *testing.T) {
	orgID, wsID, wsRepo, profileRepo, setRepo, questionRepo, answerRepo, docRepo := setupGenerateFixture(t)

	docRepo.On("Create", orgContext(orgID), mock.AnythingOfType("*model.GeneratedDocument")).
		Run(func(args mock.Arguments) {
			doc := args.Get(1).(*docModel.GeneratedDocument)
			assert.Equal(t, wsID, doc.WorkspaceID)
			assert.Equal(t, orgID, doc.OrganizationID)
			assert.Equal(t, docModel.StatusSucceeded, doc.Status)
			assert.Equal(t, "mock", doc.ProviderName)
			assert.Contains(t, doc.MarkdownBody, "Studio Document")
			assert.NotEmpty(t, doc.SourceFingerprint)
		}).
		Return(nil)

	provider := &stubLLMProvider{
		name: "mock",
		resp: llm.GenerateResponse{
			Content:  "# Studio Document\n\nGenerated by mock provider.\n",
			Provider: "mock",
			Model:    "mock-model",
		},
	}

	uc := NewGenerateDocumentUseCase(
		NewWorkspaceContextBuilder(wsRepo, profileRepo, setRepo, questionRepo, answerRepo),
		NewPromptBuilder(),
		provider,
		docRepo,
		NewGenerationGate(),
		true,
		nil,
	)

	out, err := uc.Execute(orgContext(orgID), wsID, dto.GenerateDocumentRequest{Title: "My Doc"})
	require.NoError(t, err)
	require.NotNil(t, out)
	assert.Equal(t, "My Doc", out.Title)
	assert.Equal(t, "tr", out.Language)
	assert.Equal(t, docModel.StatusSucceeded, out.Status)
	assert.Contains(t, out.MarkdownBody, "Studio Document")
	docRepo.AssertExpectations(t)
}

func TestGenerateDocument_DisabledReturns503(t *testing.T) {
	_, wsID, wsRepo, profileRepo, setRepo, questionRepo, answerRepo, docRepo := setupGenerateFixture(t)
	uc := NewGenerateDocumentUseCase(
		NewWorkspaceContextBuilder(wsRepo, profileRepo, setRepo, questionRepo, answerRepo),
		NewPromptBuilder(),
		&stubLLMProvider{name: "mock"},
		docRepo,
		NewGenerationGate(),
		false,
		nil,
	)
	_, err := uc.Execute(orgContext(uuid.New()), wsID, dto.GenerateDocumentRequest{})
	require.Error(t, err)
	assert.True(t, errors.Is(err, domainErr.ErrServiceUnavailable))
}

func TestGenerateDocument_RejectsOverlappingRequests(t *testing.T) {
	orgID, wsID, wsRepo, profileRepo, setRepo, questionRepo, answerRepo, docRepo := setupGenerateFixture(t)
	gate := NewGenerationGate()
	require.True(t, gate.TryBegin(wsID))

	uc := NewGenerateDocumentUseCase(
		NewWorkspaceContextBuilder(wsRepo, profileRepo, setRepo, questionRepo, answerRepo),
		NewPromptBuilder(),
		&stubLLMProvider{name: "mock"},
		docRepo,
		gate,
		true,
		nil,
	)
	_, err := uc.Execute(orgContext(orgID), wsID, dto.GenerateDocumentRequest{})
	require.Error(t, err)
	assert.True(t, errors.Is(err, domainErr.ErrConflict))
	gate.End(wsID)
}

func TestGenerateDocument_ProviderFailureMapsTo502AndPersistsFailedRow(t *testing.T) {
	orgID, wsID, wsRepo, profileRepo, setRepo, questionRepo, answerRepo, docRepo := setupGenerateFixture(t)

	docRepo.On("Create", orgContext(orgID), mock.AnythingOfType("*model.GeneratedDocument")).
		Run(func(args mock.Arguments) {
			doc := args.Get(1).(*docModel.GeneratedDocument)
			assert.Equal(t, docModel.StatusFailed, doc.Status)
			assert.Empty(t, doc.MarkdownBody)
			assert.Equal(t, "LLM provider failed to generate content", doc.ErrorMessage)
			assert.NotEmpty(t, doc.SourceFingerprint)
			assert.Equal(t, "mock", doc.ProviderName)
		}).
		Return(nil)

	uc := NewGenerateDocumentUseCase(
		NewWorkspaceContextBuilder(wsRepo, profileRepo, setRepo, questionRepo, answerRepo),
		NewPromptBuilder(),
		&stubLLMProvider{name: "mock", err: errors.New("upstream boom")},
		docRepo,
		NewGenerationGate(),
		true,
		nil,
	)
	_, err := uc.Execute(orgContext(orgID), wsID, dto.GenerateDocumentRequest{})
	require.Error(t, err)
	assert.True(t, errors.Is(err, domainErr.ErrBadGateway))
	docRepo.AssertExpectations(t)
}

func TestListDocuments_OmitsBodiesInSummary(t *testing.T) {
	orgID := uuid.New()
	wsID := uuid.New()
	wsRepo := new(mockWorkspaceRepo)
	docRepo := new(mockDocumentRepo)

	wsRepo.On("GetByID", orgContext(orgID), wsID).Return(&tenantModel.Workspace{
		ID: wsID, OrganizationID: orgID, Status: tenantModel.WorkspaceStatusActive,
	}, nil)

	body := "# secret-ish body"
	docRepo.On("ListByWorkspace", orgContext(orgID), wsID, 20).Return([]*docModel.GeneratedDocument{
		{
			ID: uuid.New(), WorkspaceID: wsID, OrganizationID: orgID,
			Title: "A", Status: docModel.StatusSucceeded, MarkdownBody: body,
			ProviderName: "mock", ModelName: "m",
		},
	}, nil)

	uc := NewListDocumentsUseCase(docRepo, wsRepo)
	out, err := uc.Execute(orgContext(orgID), wsID, 20)
	require.NoError(t, err)
	require.Len(t, out.Documents, 1)
	assert.Equal(t, "A", out.Documents[0].Title)
	// Summary type has no MarkdownBody field — ensure list DTO path is used.
	assert.Equal(t, "mock", out.Documents[0].ProviderName)
}

func TestGetDocument_ForeignWorkspaceForbidden(t *testing.T) {
	orgID := uuid.New()
	wsID := uuid.New()
	otherWS := uuid.New()
	docID := uuid.New()

	wsRepo := new(mockWorkspaceRepo)
	docRepo := new(mockDocumentRepo)

	wsRepo.On("GetByID", orgContext(orgID), wsID).Return(&tenantModel.Workspace{
		ID: wsID, OrganizationID: orgID, Status: tenantModel.WorkspaceStatusActive,
	}, nil)
	docRepo.On("GetByID", orgContext(orgID), docID).Return(&docModel.GeneratedDocument{
		ID: docID, WorkspaceID: otherWS, OrganizationID: orgID, MarkdownBody: "# x",
	}, nil)

	uc := NewGetDocumentUseCase(docRepo, wsRepo)
	_, err := uc.Execute(orgContext(orgID), wsID, docID)
	require.Error(t, err)
	assert.True(t, errors.Is(err, domainErr.ErrForbidden))
}
