// OpenAI-compatible mock LLM for local Compose (dev/staging without GPU).
// Replace with a real mlc-llm image in production GPU environments.
package main

import (
	"encoding/json"
	"log"
	"net/http"
	"strings"
	"time"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	mux.HandleFunc("/v1/chat/completions", handleChatCompletions)
	mux.HandleFunc("/v1/models", func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{
			"object": "list",
			"data": []map[string]string{
				{"id": "mock-mlc-model", "object": "model"},
			},
		})
	})

	addr := ":8080"
	log.Printf("mock-llm listening on %s", addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatal(err)
	}
}

type chatRequest struct {
	Model    string `json:"model"`
	Messages []struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	} `json:"messages"`
}

func handleChatCompletions(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	var req chatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid json", http.StatusBadRequest)
		return
	}
	model := strings.TrimSpace(req.Model)
	if model == "" {
		model = "mock-mlc-model"
	}
	content := mockResponseContent(req.Messages)
	writeJSON(w, http.StatusOK, map[string]any{
		"id":      "chatcmpl-mock",
		"object":  "chat.completion",
		"created": time.Now().Unix(),
		"model":   model,
		"choices": []map[string]any{
			{
				"index": 0,
				"message": map[string]string{
					"role":    "assistant",
					"content": content,
				},
				"finish_reason": "stop",
			},
		},
	})
}

func mockResponseContent(messages []struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}) string {
	for _, msg := range messages {
		if strings.Contains(msg.Content, "product_spec") ||
			strings.Contains(msg.Content, "Belge tipi: product_spec") ||
			strings.Contains(msg.Content, "Document type: product_spec") {
			return productSpecMarkdown("PEFT Smoke Test")
		}
	}
	return "# Studio Document\n\nGenerated by mock MLC-compatible server for Compose.\n"
}

func productSpecMarkdown(projectName string) string {
	return `# Ürün Spesifikasyonu: ` + projectName + `

## 1. Özet ve hedef kullanıcı
Bu belge mock LLM tarafından üretilmiş izole PEFT smoke test verisidir.
Hedef kullanıcı, ürün spesifikasyonlarını onaylayan geliştirme ve ürün ekipleridir.

## 2. Problem tanımı ve kapsam
Onaylı product_spec belgelerinden offline JSONL export pipeline'ının uçtan uca doğrulanması gerekiyor.
Kapsam: fingerprint gate, kalite gate, train/val split ve manifest yazımı.

## 3. Ürün gereksinimleri
- CLI tabanlı export (HTTP API değil)
- Approved + succeeded + product_spec filtresi
- Prompt rebuild ile messages dizisi
- Minimum kalite skoru ve bölüm kapsamı kontrolü

## 4. Mimari kararlar
Clean/hexagonal mimari; Postgres repository; export use case orchestration.
PromptBuilder ve WorkspaceContextBuilder generate akışı ile paylaşılır.

## 5. AI / LLM kullanımı
Generate aşamasında mock LLM kullanılır; export sırasında assistant gövdesi DB'den okunur.
Sistem ve kullanıcı promptları export anında yeniden üretilir.

## 6. MCP ve otomasyon entegrasyonları
MCP katmanı agent erişimi için planlanmıştır; bu smoke verisi entegrasyon detayı içermez.

## 7. Güvenlik ve uyumluluk
Multi-tenant org izolasyonu; JWT auth; mevcut production kayıtları değiştirilmez.

## 8. Gözlemlenebilirlik ve operasyon
Export manifest skip_reasons içerir; dry-run modu aday sayısını raporlar.

## 9. Açık sorular ve eksikler
Gerçek LLM çıktısı ile tam entegrasyon testi ayrı fazda yapılacaktır.
`
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}
