apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: masterfabric
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: masterfabric-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - masterfabric-nginx:8080
            labels:
              service: masterfabric-api
