apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: masterfabric
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: logging
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.3.2
          args:
            - -config.file=/etc/loki/loki-config.yml
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yml
              subPath: loki-config.yml
            - name: loki-data
              mountPath: /loki
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}
