apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: masterfabric-ingress
  namespace: masterfabric
  labels:
    app.kubernetes.io/name: masterfabric
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "130"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: api.masterfabric.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: masterfabric-nginx
                port:
                  number: 8080
    - host: grafana.masterfabric.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
