apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: masterfabric

resources:
  - namespace.yaml
  - secret-api.yaml
  - configmap-nginx.yaml
  - configmap-prometheus.yaml
  - configmap-grafana.yaml
  - configmap-loki.yaml
  - configmap-promtail.yaml
  - rbac-promtail.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-nginx.yaml
  - service-nginx.yaml
  - deployment-prometheus.yaml
  - service-prometheus.yaml
  - deployment-grafana.yaml
  - service-grafana.yaml
  - deployment-loki.yaml
  - service-loki.yaml
  - daemonset-promtail.yaml
  - hpa-api.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: masterfabric
    includeSelectors: false
