package mock

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/masterfabric-go/masterfabric/internal/domain/llm"
)

// Sentinel errors for controlled failure scenarios in tests.
var (
	ErrGenerationFailed = errors.New("mock provider generation failure")
	ErrHealthFailed     = errors.New("mock provider health failure")
)

// Provider is a deterministic in-process LLMProvider for tests and local development.
// It never calls external networks.
type Provider struct {
	mu sync.RWMutex

	model string

	failGenerate error
	failHealth   error
	delay        time.Duration
}

// Option configures a mock Provider.
type Option func(*Provider)

// WithModel sets the model name reported in GenerateResponse.
func WithModel(model string) Option {
	return func(p *Provider) {
		if model != "" {
			p.model = model
		}
	}
}

// WithGenerateError forces Generate to return the given error (after context checks).
func WithGenerateError(err error) Option {
	return func(p *Provider) {
		p.failGenerate = err
	}
}

// WithHealthError forces Health to return the given error (after context checks).
func WithHealthError(err error) Option {
	return func(p *Provider) {
		p.failHealth = err
	}
}

// WithDelay waits up to d before completing Generate/Health, honouring context cancel.
func WithDelay(d time.Duration) Option {
	return func(p *Provider) {
		p.delay = d
	}
}

// New creates a mock LLM provider.
func New(opts ...Option) *Provider {
	p := &Provider{model: "mock-model"}
	for _, opt := range opts {
		opt(p)
	}
	return p
}

// SetGenerateError updates the controlled generation failure (nil clears it).
func (p *Provider) SetGenerateError(err error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.failGenerate = err
}

// SetHealthError updates the controlled health failure (nil clears it).
func (p *Provider) SetHealthError(err error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.failHealth = err
}

// Name implements llm.LLMProvider.
func (p *Provider) Name() string {
	return llm.ProviderMock
}

// Generate implements llm.LLMProvider with deterministic Markdown output.
func (p *Provider) Generate(ctx context.Context, req llm.GenerateRequest) (llm.GenerateResponse, error) {
	if err := waitOrDone(ctx, p.delayLocked()); err != nil {
		return llm.GenerateResponse{}, err
	}

	p.mu.RLock()
	fail := p.failGenerate
	model := p.model
	p.mu.RUnlock()

	if fail != nil {
		return llm.GenerateResponse{}, fail
	}

	// Deterministic content: lengths only — never echo prompt bodies (secrets-safe).
	content := fmt.Sprintf(
		"# Studio Document\n\nGenerated by mock provider.\n\n"+
			"<!-- meta:system_bytes=%d user_bytes=%d max_tokens=%d -->\n",
		len(req.SystemPrompt),
		len(req.UserPrompt),
		req.MaxTokens,
	)

	return llm.GenerateResponse{
		Content:      content,
		Provider:     p.Name(),
		Model:        model,
		FinishReason: "stop",
		Usage: llm.TokenUsage{
			PromptTokens:     len(req.SystemPrompt) + len(req.UserPrompt),
			CompletionTokens: len(content),
			TotalTokens:      len(req.SystemPrompt) + len(req.UserPrompt) + len(content),
		},
	}, nil
}

// Health implements llm.LLMProvider.
func (p *Provider) Health(ctx context.Context) (llm.ProviderHealth, error) {
	if err := waitOrDone(ctx, p.delayLocked()); err != nil {
		return llm.ProviderHealth{}, err
	}

	p.mu.RLock()
	fail := p.failHealth
	p.mu.RUnlock()

	if fail != nil {
		return llm.ProviderHealth{}, fail
	}

	return llm.ProviderHealth{
		Provider: p.Name(),
		Healthy:  true,
		Message:  "ok",
	}, nil
}

func (p *Provider) delayLocked() time.Duration {
	p.mu.RLock()
	defer p.mu.RUnlock()
	return p.delay
}

func waitOrDone(ctx context.Context, delay time.Duration) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if delay <= 0 {
		return ctx.Err()
	}
	timer := time.NewTimer(delay)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return ctx.Err()
	}
}

// Compile-time check.
var _ llm.LLMProvider = (*Provider)(nil)
